In [2]:
import numpy as np

In [3]:
list_1 = [2,4,6,8,10]
x = np.array(list_1)
print(x)
print(type(x))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [4]:
list_2 = [[1,2,3],[4,5,6]]
y = np.array(list_2)
print(y)

[[1 2 3]
 [4 5 6]]


In [8]:
list_3 = [[[1,2],[3,4]],[[2,4],[6,8]],[[1,3],[5,7]]]
z = np.array(list_3)
z

array([[[1, 2],
        [3, 4]],

       [[2, 4],
        [6, 8]],

       [[1, 3],
        [5, 7]]])

In [9]:
a = np.linspace(start=0, stop=100, num=21)
a

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [12]:
b = np.array([1,0,4,1,1,0], dtype='bool')
b

array([ True, False,  True,  True,  True, False])

In [13]:
c = np.zeros((4,), dtype='int')
c

array([0, 0, 0, 0])

In [16]:
d = np.zeros((3,2), dtype='int')
d

array([[0, 0],
       [0, 0],
       [0, 0]])

In [22]:
e = np.empty((3,))
e

array([3., 2., 1.])

In [23]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
v.shape

(3, 3)

In [24]:
u = np.zeros_like(v)
u

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
z = np.zeros(v.shape, dtype='bool')

z

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [28]:
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
i1 = np.eye(5)
i1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
ab = np.arange(0, 30, 5)
ab

array([ 0,  5, 10, 15, 20, 25])

In [5]:
ar1 = np.arange(5)
ar1

array([0, 1, 2, 3, 4])

In [6]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y = np.array([[16,17,18],[10,11,12],[13,14,15]])
y

array([[16, 17, 18],
       [10, 11, 12],
       [13, 14, 15]])

In [8]:
z = x + y
z

array([[17, 19, 21],
       [14, 16, 18],
       [20, 22, 24]])

In [11]:
x2 = np.stack((x, y), axis=0)
x2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[16, 17, 18],
        [10, 11, 12],
        [13, 14, 15]]])

In [29]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[9,7]])
x4 = np.array([[10,11],[12,13]])
x3 = np.stack((x1, x2, x4), axis=0)
x3.shape
print(x3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 9  7]]

 [[10 11]
  [12 13]]]


In [56]:
x5 = np.arange(10,16).reshape(2,3)
x5

array([[10, 11, 12],
       [13, 14, 15]])

In [59]:
x7 = np.column_stack((x1, x5))
x7

array([[ 1,  2, 10, 11, 12],
       [ 3,  4, 13, 14, 15]])

In [62]:
print(x1)
print(x5)

[[1 2]
 [3 4]]
[[10 11 12]
 [13 14 15]]


In [57]:
x6 = np.hstack((x1, x5))
x6

array([[ 1,  2, 10, 11, 12],
       [ 3,  4, 13, 14, 15]])

In [72]:
x = np.array([[1,1,1],[2,2,2]])

x + 1

array([[2, 2, 2],
       [3, 3, 3]])

In [65]:
y = np.array([[1,2,3]])
y.shape

(3,)

In [67]:
x + y

array([[2, 4, 6],
       [1, 1, 4]])

In [76]:
z = np.array([[10],[20]])

w=x+z

In [77]:
w.T

array([[11, 22],
       [11, 22],
       [11, 22]])

In [78]:
x.T

array([[1, 2],
       [1, 2],
       [1, 2]])

In [79]:
print(x)
print(y)

print(x-y)

[[1 1 1]
 [2 2 2]]
[1 2 3]
[[ 0 -1 -2]
 [ 1  0 -1]]


In [80]:
print(x)
print(z)

print(x-z)

[[1 1 1]
 [2 2 2]]
[[10]
 [20]]
[[ -9  -9  -9]
 [-18 -18 -18]]


In [83]:
def return_max_value(a, b):
    if a > b:
        return a
    else:
        return b

In [87]:
array1 = np.array([[3,5,6]])
array2 = np.array([[5,1,7]])

return_max_value_vect = np.vectorize(return_max_value)

return_max_value_vect(array1, array2)


array([[5, 5, 7]])