In [1]:
import numpy as np

In [3]:
list_1 = [2,4,6,8,10]
x = np.array(list_1)
print(x)
print(type(x))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [5]:
list_2 = [[1,2,3],[4,5,6]]
y = np.array(list_2)
print(y)

[[1 2 3]
 [4 5 6]]


In [8]:
list_3 = [[[1,2],[3,4]],[[2,4],[6,8]],[[1,3],[5,7]]]
z = np.array(list_3)
z

array([[[1, 2],
        [3, 4]],

       [[2, 4],
        [6, 8]],

       [[1, 3],
        [5, 7]]])

In [9]:
a = np.linspace(start=0, stop=100, num=21)
a

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [12]:
b = np.array([1,0,4,1,1,0], dtype='bool')
b

array([ True, False,  True,  True,  True, False])

In [13]:
c = np.zeros((4,), dtype='int')
c

array([0, 0, 0, 0])

In [16]:
d = np.zeros((3,2), dtype='int')
d

array([[0, 0],
       [0, 0],
       [0, 0]])

In [22]:
e = np.empty((3,))
e

array([3., 2., 1.])

In [23]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
v.shape

(3, 3)

In [24]:
u = np.zeros_like(v)
u

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
z = np.zeros(v.shape, dtype='bool')

z

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [28]:
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
i1 = np.eye(5)
i1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
ab = np.arange(0, 30, 5)
ab

array([ 0,  5, 10, 15, 20, 25])